// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvwsh4E-WLA_aRvtSYSbVzx3HmdfKNJfI',
    appId: '1:214241196372:web:fbdf64f92bd880258630c1',
    messagingSenderId: '214241196372',
    projectId: 'crudapp-c9397',
    authDomain: 'crudapp-c9397.firebaseapp.com',
    storageBucket: 'crudapp-c9397.appspot.com',
    measurementId: 'G-9QB7GX0S3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWCdY0iozAkWa3J13Z1t0n5RBwPIidZ7I',
    appId: '1:214241196372:android:a5794e0d74161ed68630c1',
    messagingSenderId: '214241196372',
    projectId: 'crudapp-c9397',
    storageBucket: 'crudapp-c9397.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANdIR8OkN95K13NxC2haQ6YOS_OUgxR6Y',
    appId: '1:214241196372:ios:802a016264a7e4288630c1',
    messagingSenderId: '214241196372',
    projectId: 'crudapp-c9397',
    storageBucket: 'crudapp-c9397.appspot.com',
    iosBundleId: 'com.example.crudapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANdIR8OkN95K13NxC2haQ6YOS_OUgxR6Y',
    appId: '1:214241196372:ios:07f5449a5827b1a68630c1',
    messagingSenderId: '214241196372',
    projectId: 'crudapp-c9397',
    storageBucket: 'crudapp-c9397.appspot.com',
    iosBundleId: 'com.example.crudapp.RunnerTests',
  );
}
